# Generated by Django 3.0.7 on 2020-07-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_auto_20200716_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='urlSitio',
            field=models.TextField(blank=True, null=True, verbose_name='url'),
        ),
    ]
